language: node_js
node_js: '6'
branches:
  only:
  - master
env:
  global:
  - ENCRYPTION_LABEL: d93a415ead41
  - DEPLOY_BRANCH: master
  - SOURCE_DIR: e2e_output/report
  - TARGET_BRANCH: gh-pages
  - SSH_KEY: id_rsa
  - GIT_NAME: travis
  - GIT_EMAIL: deploy@travis-ci.org
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    env: BROWSER=firefox
  exclude:
  - node_js: stable
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  firefox: '46.0'
cache:
  directories:
  - node_modules
before_script:
- export DISPLAY=:99.0
- "./script/travis-build.sh"
- chmod +x ./decrypt.sh
- "./decrypt.sh"
- yarn
script:
- node ./node_modules/.bin/chimp ./chimp.conf.js --browser ${BROWSER}
- npm run report
after_script: node_modules/.bin/gh-pages-travis
notifications:
  email:
    on_success: never
    on_failure: change
