language: node_js
node_js: "6"

branches:
  only:
    - master

env:
  global:
    - ENCRYPTION_LABEL: "ae8e44dcec30"
    - COMMIT_AUTHOR_EMAIL: "ryan.park@unosquare.com"

matrix:
  include:
    # - os: linux
    #   dist: trusty
    #   sudo: required
    #   env: BROWSER=firefox
    - os: linux
      dist: trusty
      sudo: required
      env: BROWSER=chrome
    # - os: osx
    #   osx_image: xcode8
    #   env: BROWSER=firefox
    # - os: osx
    #   osx_image: xcode8
    #   env: BROWSER=chrome
  exclude:
    - node_js: "stable"


addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  firefox: "46.0"

cache:
  directories:
    - node_modules

before_script:
    - export DISPLAY=:99.0
    - ./script/travis-build.sh
    - yarn

script: 
  - node ./node_modules/.bin/chimp --browser ${BROWSER}
  - npm run report

deploy:
  local_dir: './e2e_output/report'
  provider: pages
  skip_cleanup: true
  github_token: $encrypted_ae8e44dcec30_key # Set in travis-ci.org dashboard
  on:
    branch: master


notifications:
  email:
    on_success: never
    on_failure: change

