language: node_js
node_js: "6"

branches:
  only:
    - master

env:
  global:
    - DEPLOY_BRANCH: "master"
    - SOURCE_DIR: "e2e_output/report"
    - TARGET_BRANCH: "gh-pages"
    - SSH_KEY: "deploy"
    - GIT_NAME: "travis"
    - GIT_EMAIL: "deploy@travis-ci.org"

before_install:
  - openssl aes-256-cbc -K ${encrypted_ae8e44dcec30_key} -iv ${encrypted_ae8e44dcec30_iv} -in ./deploy.enc -out ./deploy -d

matrix:
  include:
    # - os: linux
    #   dist: trusty
    #   sudo: required
    #   env: BROWSER=firefox
    - os: linux
      dist: trusty
      sudo: required
      env: BROWSER=firefox
    # - os: osx
    #   osx_image: xcode8
    #   env: BROWSER=firefox
    # - os: osx
    #   osx_image: xcode8
    #   env: BROWSER=chrome
  exclude:
    - node_js: "stable"


addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  firefox: "46.0"

cache:
  directories:
    - node_modules

before_script:
    - export DISPLAY=:99.0
    - ./script/travis-build.sh
    - yarn

script: 
  - node ./node_modules/.bin/chimp ./chimp.conf.js --browser ${BROWSER}
  - npm run report

# deploy:
#   local_dir: './e2e_output/report'
#   provider: pages
#   skip_cleanup: true
#   github_token: $gh-key # Set in travis-ci.org dashboard

after_script: node_modules/.bin/gh-pages-travis

notifications:
  email:
    on_success: never
    on_failure: change

